# Generated by Django 3.2 on 2021-07-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pcs',
            field=models.CharField(default=' ', max_length=100, verbose_name='pcs'),
            preserve_default=False,
        ),
    ]
