# Generated by Django 3.2 on 2021-07-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_client_pcs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='spareparts',
        ),
        migrations.DeleteModel(
            name='tool',
        ),
    ]
